.PHONY: clean All

All:
	@echo "----------Building project:[ apt32s1028 - BuildSet ]----------"
	@
	@cd "F:\OneDrive\APT\APT_MCU_IC\Demo_code\APT32F102\APT32S1028_Release_V1_09\Source" && make -f "apt32s1028.mk" MakeIntermediateDirs && make -f "apt32s1028.mk" -j 6
clean:
	@echo "----------Cleaning project:[ apt32s1028 - BuildSet ]----------"
	@cd "F:\OneDrive\APT\APT_MCU_IC\Demo_code\APT32F102\APT32S1028_Release_V1_09\Source" && make -f  "apt32s1028.mk" clean
